# Generated by Django 4.2.5 on 2023-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMtest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangouser',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=250),
        ),
    ]
