# Generated by Django 4.2.5 on 2023-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMtest', '0002_djangouser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangouser',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
