# Generated by Django 4.2.5 on 2023-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMtest', '0003_alter_djangouser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangouser',
            name='email',
            field=models.EmailField(default='', max_length=250),
        ),
    ]
