# Generated by Django 4.2.5 on 2023-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORMtest', '0004_alter_djangouser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangouser',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='djangouser',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='djangouser',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
